version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/backend:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/simplerag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=simplerag
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=False
      - API_PREFIX=/api
      - BACKEND_CORS_ORIGINS=["https://${DOMAIN}", "http://frontend:3000"]
      - EMBEDDING_MODEL=text-embedding-ada-002
    depends_on:
      - db
    networks:
      - simplerag-network

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/frontend:latest
    restart: always
    environment:
      - VITE_API_URL=https://${DOMAIN}/api
    depends_on:
      - backend
    networks:
      - simplerag-network

  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=simplerag
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - simplerag-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend
    networks:
      - simplerag-network

volumes:
  postgres-data:

networks:
  simplerag-network:
    driver: bridge

