version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/simplerag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplerag
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=True
      - API_PREFIX=/api
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:5173", "http://frontend:3000"]
      - EMBEDDING_MODEL=text-embedding-ada-002
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - simplerag-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - simplerag-network

  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simplerag
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - simplerag-network

volumes:
  postgres-data:

networks:
  simplerag-network:
    driver: bridge

